# Setup ACL

- name: Create rule `to-svr`
  vyos.vyos.vyos_config:
    lines:
      - set firewall ipv4 name to-svr default-action drop
      # 10
      - set firewall ipv4 name to-svr rule 10 description Permit-ICMP
      - set firewall ipv4 name to-svr rule 10 protocol icmp
      - set firewall ipv4 name to-svr rule 10 action accept
      # 50
      - set firewall ipv4 name to-svr rule 50 description Permit-HTTP
      - set firewall ipv4 name to-svr rule 50 protocol tcp
      - set firewall ipv4 name to-svr rule 50 destination address 192.168.52.128
      - set firewall ipv4 name to-svr rule 50 destination port 80
      - set firewall ipv4 name to-svr rule 50 action accept
      # 51
      - set firewall ipv4 name to-svr rule 51 description Permit-HTTPS
      - set firewall ipv4 name to-svr rule 51 protocol tcp
      - set firewall ipv4 name to-svr rule 51 destination address 192.168.52.128
      - set firewall ipv4 name to-svr rule 51 destination port 443
      - set firewall ipv4 name to-svr rule 51 action accept

- name: Create rule `to-cli`
  vyos.vyos.vyos_config:
    lines:
      - set firewall ipv4 name to-cli default-action accept

- name: Set firewall rule
  vyos.vyos.vyos_config:
    lines:
      # Define zones
      - set firewall zone client interface eth1
      - set firewall zone server interface eth2
      # Set rule
      - set firewall zone server from client firewall name to-svr
      - set firewall zone client from server firewall name to-cli
