# Setup crypto-policies

- name: Upload policy of crypto-policies
  ansible.builtin.copy:
    src: ICTSC.pol
    dest: /etc/crypto-policies/policies/ICTSC.pol
    mode: '0600'
    backup: true

- name: Check current policy of crypto-policies
  ansible.builtin.command: update-crypto-policies --show
  register: current_policy
  changed_when: false

- name: Switch policy of crypto-policies
  ansible.builtin.command: update-crypto-policies --set ICTSC
  when: current_policy.stdout != "ICTSC"
  changed_when: true
  notify: Reboot

- name: Check does crypto-policies match
  ansible.builtin.command: update-crypto-policies --check
  register: policy_match
  changed_when: false
  ignore_errors: true

- name: Switch policy of crypto-policies
  ansible.builtin.command: update-crypto-policies --set ICTSC
  when: policy_match.rc != 0
  changed_when: true
  notify: Reboot
