- name: Setup Client
  hosts:
    - client
  become: true
  roles:
    - client_ssh

- name: Setup Router
  hosts:
    - router
  connection: network_cli
  vars:
    ansible_network_os: vyos
  roles:
    - vyos_router
    - acl

- name: Setup Server
  hosts:
    - server
  become: true
  roles:
    - trouble_user
    - crypto_policies
