# Wait for ssh connection
- name: Wait for SSH connection
  hosts: server
  gather_facts: false
  tasks:
    - name: Wait for SSH connection
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 300

- name: Setup Router
  hosts:
    - router
  connection: network_cli
  vars:
    ansible_network_os: vyos
  roles:
    - vyos_router
    - acl

- name: Setup Server
  hosts:
    - server
  become: true
  roles:
    - trouble_user
    - crypto_policies
