- name: Apply netplan
  ansible.builtin.command: netplan apply
  changed_when: true

- name: Restart NetworkManager
  ansible.builtin.systemd_service:
    name: NetworkManager.service
    state: restarted
